on:
  push:
    branches:
      -master
name: Deploy website on CPanel
jobs:
  FTP-deploy:
    name: FTP-deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2.1.0
      
    - name: ðŸ“‚ FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
